@startuml


actor User as U
participant App as A
boundary Edge as E
participant "Backbase blade" as BB
database Credentials as C
participant Plaid as P
collections Banks


U -> A: Link Accounts (Create item)
note left
select wanted products
(fills credentials)
available banks returned
select wanted bank

end note
activate A
A -> P: link initialise https://cdn.plaid.com/link/v2/stable/link-initialize.js
activate P
P-->A: complete
BB->P:POST info http://localhost:8000/api/info
P-->BB: response item info

deactivate
BB->P: Request link_token POST http://localhost:8000/api/create_link_token
activate P
P-->BB:return link_token
deactivate P
BB->A: open link
activate A
P->A: display banks to user https://sandbox.plaid.com/link/client/get
deactivate A
A->P:create item https://sandbox.plaid.com/link/item/create
activate P
P-> A : Public_token
note right
cant be going
to and from the right place
but definatly happens
end note
deactivate P
A->P:https://sandbox.plaid.com/link/item/mfa
activate P
P->A:response
deactivate P

note left
should pass
link_token to apps client
and used to initialise Link
end note
A->U: ask user to connect
BB->A:open link (initialise)????
activate A

note left
user authenticates
and creates item?
end note

A->BB:onSuccess()
note right
once item created public
and access token exchange
end note
deactivate A

note left
in the on success call back
public_token is sent to apps
server
end note
BB->P:http://localhost:8000/api/set_access_token pulic token

activate P

note right
exchanged for
access_token
end note


P-->BB: access_token & item_id
deactivate P

BB->C: store access_token & item_id
BB->Banks:product requests using access_token & item_id & secret
activate Banks
Banks--> BB: response to request
deactivate Banks
deactivate A
A -> U: Accounts

@enduml